version: '{build}'

before_build:
  - dotnet restore

build_script:
  - dotnet build src\FileSignatures -c Release

after_build:
  - dotnet pack src\FileSignatures -c Release -o ..\..\artifacts

test_script:
  # Workaround until appveyor/ci#1404 is resolved
  - cd test\FileSignatures.Tests
  - dotnet test

artifacts:
  - path: '.\artifacts\*.nupkg'
    name: NuGet Package

deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: Br035jyTit8hIaWNRZl10uL5LZIYTVtN2NF4jOwfisuEfA3SadxoCM/p1mpe5j+Y
    on:
      appveyor_repo_tag: true
